// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TarpinisAtsiskaitymasAdasDB.Data;

#nullable disable

namespace TarpinisAtsiskaitymasAdasDB.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DepartmentLectures", b =>
                {
                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LectureName")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartmentCode", "LectureName");

                    b.HasIndex("LectureName");

                    b.ToTable("DepartmentLectures");

                    b.HasData(
                        new
                        {
                            DepartmentCode = "CS1234",
                            LectureName = "Algorithms"
                        },
                        new
                        {
                            DepartmentCode = "CS1234",
                            LectureName = "DataStructures"
                        },
                        new
                        {
                            DepartmentCode = "MTH567",
                            LectureName = "Calculus"
                        });
                });

            modelBuilder.Entity("StudentLectures", b =>
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("LectureName")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentNumber", "LectureName");

                    b.HasIndex("LectureName");

                    b.ToTable("StudentLectures");

                    b.HasData(
                        new
                        {
                            StudentNumber = 12345678,
                            LectureName = "Algorithms"
                        },
                        new
                        {
                            StudentNumber = 12345678,
                            LectureName = "DataStructures"
                        },
                        new
                        {
                            StudentNumber = 87654321,
                            LectureName = "Calculus"
                        });
                });

            modelBuilder.Entity("TarpinisAtsiskaitymasAdasDB.Entities.Department", b =>
                {
                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentCode");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentCode = "CS1234",
                            DepartmentName = "ComputerScience"
                        },
                        new
                        {
                            DepartmentCode = "MTH567",
                            DepartmentName = "Mathematics"
                        });
                });

            modelBuilder.Entity("TarpinisAtsiskaitymasAdasDB.Entities.Lecture", b =>
                {
                    b.Property<string>("LectureName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LectureDay")
                        .HasColumnType("int");

                    b.Property<string>("LectureTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LectureName");

                    b.ToTable("Lectures");

                    b.HasData(
                        new
                        {
                            LectureName = "Algorithms",
                            LectureTime = "10:00-11:30"
                        },
                        new
                        {
                            LectureName = "Calculus",
                            LectureTime = "12:00-13:30"
                        },
                        new
                        {
                            LectureName = "DataStructures",
                            LectureTime = "14:00-15:30"
                        });
                });

            modelBuilder.Entity("TarpinisAtsiskaitymasAdasDB.Entities.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentNumber");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentNumber = 12345678,
                            DepartmentCode = "CS1234",
                            Email = "john.smith@example.com",
                            FirstName = "John",
                            LastName = "Smith"
                        },
                        new
                        {
                            StudentNumber = 87654321,
                            DepartmentCode = "MTH567",
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson"
                        });
                });

            modelBuilder.Entity("DepartmentLectures", b =>
                {
                    b.HasOne("TarpinisAtsiskaitymasAdasDB.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarpinisAtsiskaitymasAdasDB.Entities.Lecture", null)
                        .WithMany()
                        .HasForeignKey("LectureName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentLectures", b =>
                {
                    b.HasOne("TarpinisAtsiskaitymasAdasDB.Entities.Lecture", null)
                        .WithMany()
                        .HasForeignKey("LectureName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarpinisAtsiskaitymasAdasDB.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarpinisAtsiskaitymasAdasDB.Entities.Student", b =>
                {
                    b.HasOne("TarpinisAtsiskaitymasAdasDB.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TarpinisAtsiskaitymasAdasDB.Entities.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
